# DKMS configuration for Thunderobot platform modules
PACKAGE_NAME="thunderobot"
PACKAGE_VERSION="1.1.0"

MAKE="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
CLEAN="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"

BUILT_MODULE_NAME[0]=thunderobot

DEST_MODULE_LOCATION[0]=/kernel/drivers/platform/x86

AUTOINSTALL=yes
